const Map<String, String> secondaryFr = {
  'reengage_title': 'Relance clients WhatsApp',
  'reengage_open_whatsapp': 'Ouvrir WhatsApp',
  'reengage_campaign_done':
      'Campagne terminée. Prochaine relance possible dans 7 jours.',
  'reengage_antispam_limit': 'Limite anti-spam',
  'reengage_next_campaign_in': 'Prochaine campagne dans {days} jour(s).',
  'reengage_message_label': 'Message',
  'reengage_message_hint': 'Votre message de relance…',
  'reengage_limits_info':
      'Max {max} contacts · 1 campagne / {days} jours',
  'reengage_consent_title': 'Consentement',
  'reengage_consent_subtitle':
      'Je confirme que ces clients ont déjà contacté ma boutique et acceptent de recevoir des nouveautés.',
  'reengage_eligible_clients': 'Clients éligibles ({count})',
  'reengage_no_clients':
      'Aucun client avec numéro enregistré. Les contacts apparaîtront après commandes ou messages.',
  'reengage_client_title': 'Client {current}/{total}',
  'reengage_client_dialog':
      'Ouvrir WhatsApp pour +{phone} ?\n\nAppuyez sur « Suivant » après l\'envoi.',
  'reengage_send_progress': 'Envoi {current}/{total}…',
  'reengage_launch': 'Lancer la relance ({count})',
  'share_shop_title': 'Partager {name}',
  'share_choose_option': 'Choisissez une option de partage',
  'share_catalog_title': 'Partager le catalogue',
  'share_catalog_subtitle': 'Produits et arrivages avec liens',
  'share_link_title': 'Partager le lien',
  'share_qr_title': 'QR Code de la boutique',
  'share_qr_subtitle': 'Afficher, partager ou imprimer',
  'location_security_body':
      'Pour des raisons de sécurité, nous vous recommandons de prendre la localisation de votre entreprise et non de votre domicile.',
  'location_security_footer':
      'Cette localisation sera visible par les clients potentiels pour les aider à trouver votre boutique.',
  'location_capture_question':
      'Voulez-vous capturer votre position actuelle pour aider les clients à trouver votre boutique ?',
  'location_business_hint':
      'Utilisez la localisation de votre entreprise, pas votre domicile.',
  'location_capturing': 'Capturer la position...',
  'location_please_wait': 'Veuillez patienter quelques secondes',
  'location_coords': 'Lat: {lat}, Lng: {lng}',
  'location_accuracy': 'Précision: ±{meters} mètres',
  'edit_password_title': 'Modifier le mot de passe',
  'edit_action': 'Modifier',
  'already_have_account': 'J\'ai déjà un compte',
  'delete_product_confirm':
      'Voulez-vous vraiment supprimer ce produit ?',
  'delete_product_named':
      'Voulez-vous vraiment supprimer « {name} » ?',
  'no_photo': 'Aucune photo',
  'no_photo_body':
      'Les produits avec photos se vendent beaucoup mieux. Voulez-vous quand même continuer sans photo ?',
  'continue_without_photo': 'Continuer sans photo',
  'display_options': 'Options d\'affichage',
  'hide_price': 'Masquer le prix',
  'show_stock': 'Afficher le stock',
  'show_stock_subtitle': 'Affiche le nombre d\'articles restants',
  'flash_offer': 'Offre flash',
  'flash_offer_subtitle':
      'Badge promo sur le produit et visuels WhatsApp auto',
  'flash_offer_end': 'Fin de l\'offre',
  'promo_price_label': 'Prix promo (CDF)',
  'tier_label': 'Palier',
  'retail_type': 'Détail',
  'wholesale_type': 'Gros',
  'take_photo': 'Prendre une photo',
  'choose_from_gallery': 'Choisir dans la galerie',
  'filter_all': 'Tout',
  'choose_product': 'Choisir un produit',
  'resell_product': 'Remettre en vente',
  'login_deliveries_required':
      'Connectez-vous pour voir vos livraisons',
  'post_whatsapp_status': 'Poster mon statut WhatsApp',
  'shop_active_badge': 'Active',
  'shop_visible_badge': 'Visible',
  'shop_hidden_badge': 'Masquée',
  'today_label': 'Aujourd\'hui',
  'request_action': 'Demander',
  'whatsapp_label': 'WhatsApp',
  'more_items': '+ {count} autre(s)...',
  'expected_balance': 'Solde attendu: {amount} CDF',
  'session_since': 'Depuis {date}',
  'sync_failed': 'Échec de synchronisation : {error}',
  'error_with_message': 'Erreur : {message}',
  'sold_badge': 'VENDU',
  'photo_label': 'Photo',
  'or_label': 'ou',
  'clear_all_media': 'Effacer tout',
  'select_photo_label': 'Photo',
  'permission_location_refused': 'Permission de localisation refusée.',
  'next_button': 'Suivant',
  'sync_diagnostics': 'Diagnostics de synchronisation',
  'manual_sync': 'Synchronisation manuelle',
  'force_push_all': 'Forcer l\'envoi complet',
  'full_reset_sync': 'Réinitialiser et synchroniser',
  'queue_status': 'État de la file',
  'view_queue_details': 'Voir la file d\'attente',
  'open_whatsapp': 'Ouvrir WhatsApp',
  'share_impossible_colon': 'Partage impossible : {error}',
  'action_impossible_colon': 'Action impossible : {error}',
  'interactions_count': '{count} interaction(s)',
};

const Map<String, String> secondaryEn = {
  'reengage_title': 'WhatsApp client follow-up',
  'reengage_open_whatsapp': 'Open WhatsApp',
  'reengage_campaign_done':
      'Campaign complete. Next follow-up possible in 7 days.',
  'reengage_antispam_limit': 'Anti-spam limit',
  'reengage_next_campaign_in': 'Next campaign in {days} day(s).',
  'reengage_message_label': 'Message',
  'reengage_message_hint': 'Your follow-up message…',
  'reengage_limits_info': 'Max {max} contacts · 1 campaign / {days} days',
  'reengage_consent_title': 'Consent',
  'reengage_consent_subtitle':
      'I confirm these clients have already contacted my shop and agree to receive updates.',
  'reengage_eligible_clients': 'Eligible clients ({count})',
  'reengage_no_clients':
      'No client with a saved number. Contacts appear after orders or messages.',
  'reengage_client_title': 'Client {current}/{total}',
  'reengage_client_dialog':
      'Open WhatsApp for +{phone}?\n\nTap « Next » after sending.',
  'reengage_send_progress': 'Sending {current}/{total}…',
  'reengage_launch': 'Start follow-up ({count})',
  'share_shop_title': 'Share {name}',
  'share_choose_option': 'Choose a sharing option',
  'share_catalog_title': 'Share catalog',
  'share_catalog_subtitle': 'Products and arrivals with links',
  'share_link_title': 'Share link',
  'share_qr_title': 'Shop QR code',
  'share_qr_subtitle': 'View, share or print',
  'location_security_body':
      'For security, use your business location, not your home address.',
  'location_security_footer':
      'This location will be visible to potential customers to help them find your shop.',
  'location_capture_question':
      'Capture your current position to help customers find your shop?',
  'location_business_hint': 'Use your business location, not your home.',
  'location_capturing': 'Capturing position...',
  'location_please_wait': 'Please wait a few seconds',
  'location_coords': 'Lat: {lat}, Lng: {lng}',
  'location_accuracy': 'Accuracy: ±{meters} m',
  'edit_password_title': 'Change password',
  'edit_action': 'Edit',
  'already_have_account': 'I already have an account',
  'delete_product_confirm': 'Do you really want to delete this product?',
  'delete_product_named': 'Do you really want to delete « {name} »?',
  'no_photo': 'No photo',
  'no_photo_body':
      'Products with photos sell much better. Continue without a photo anyway?',
  'continue_without_photo': 'Continue without photo',
  'display_options': 'Display options',
  'hide_price': 'Hide price',
  'show_stock': 'Show stock',
  'show_stock_subtitle': 'Shows remaining item count',
  'flash_offer': 'Flash offer',
  'flash_offer_subtitle': 'Promo badge on product and auto WhatsApp visuals',
  'flash_offer_end': 'Offer ends',
  'promo_price_label': 'Promo price (CDF)',
  'tier_label': 'Tier',
  'retail_type': 'Retail',
  'wholesale_type': 'Wholesale',
  'take_photo': 'Take a photo',
  'choose_from_gallery': 'Choose from gallery',
  'filter_all': 'All',
  'choose_product': 'Choose a product',
  'resell_product': 'Put back on sale',
  'login_deliveries_required': 'Log in to see your deliveries',
  'post_whatsapp_status': 'Post my WhatsApp status',
  'shop_active_badge': 'Active',
  'shop_visible_badge': 'Visible',
  'shop_hidden_badge': 'Hidden',
  'today_label': 'Today',
  'request_action': 'Request',
  'whatsapp_label': 'WhatsApp',
  'more_items': '+ {count} more...',
  'expected_balance': 'Expected balance: {amount} CDF',
  'session_since': 'Since {date}',
  'sync_failed': 'Sync failed: {error}',
  'error_with_message': 'Error: {message}',
  'sold_badge': 'SOLD',
  'photo_label': 'Photo',
  'or_label': 'or',
  'clear_all_media': 'Clear all',
  'select_photo_label': 'Photo',
  'permission_location_refused': 'Location permission denied.',
  'next_button': 'Next',
  'sync_diagnostics': 'Sync diagnostics',
  'manual_sync': 'Manual sync',
  'force_push_all': 'Force push all',
  'full_reset_sync': 'Full reset & sync',
  'queue_status': 'Queue status',
  'view_queue_details': 'View queue details',
  'open_whatsapp': 'Open WhatsApp',
  'share_impossible_colon': 'Share failed: {error}',
  'action_impossible_colon': 'Action failed: {error}',
  'interactions_count': '{count} interaction(s)',
};

const Map<String, String> secondaryLn = {
  'reengage_title': 'Relance clients WhatsApp',
  'reengage_open_whatsapp': 'Fungola WhatsApp',
  'reengage_campaign_done':
      'Campagne esili. Relance elandi na mikolo 7.',
  'reengage_antispam_limit': 'Limite anti-spam',
  'reengage_next_campaign_in': 'Campagne elandi na mikolo {days}.',
  'reengage_message_label': 'Message',
  'reengage_message_hint': 'Message na yo ya relance…',
  'reengage_limits_info': 'Max {max} contacts · 1 campagne / {days} mikolo',
  'reengage_consent_title': 'Consentement',
  'reengage_consent_subtitle':
      'Nandimi que ba clients oyo basanzeli déjà boutique na ngai.',
  'reengage_eligible_clients': 'Ba clients ({count})',
  'reengage_no_clients': 'Client moko te. Ba contacts bakomonaka après commandes.',
  'reengage_client_title': 'Client {current}/{total}',
  'reengage_client_dialog':
      'Fungola WhatsApp mpo na +{phone} ?\n\nFiná « Suivant » après envoi.',
  'reengage_send_progress': 'Kotinda {current}/{total}…',
  'reengage_launch': 'Bandela relance ({count})',
  'share_shop_title': 'Partager {name}',
  'share_choose_option': 'Pona option ya partage',
  'share_catalog_title': 'Partager catalogue',
  'share_catalog_subtitle': 'Ba produits mpe arrivages na ba liens',
  'share_link_title': 'Partager lien',
  'share_qr_title': 'QR Code ya boutique',
  'share_qr_subtitle': 'Komona, partager to imprimer',
  'location_security_body':
      'Mpo na sécurité, salela position ya entreprise, esika ya ndako te.',
  'location_security_footer':
      'Position oyo ekomonana na ba clients mpo na kozwa boutique na yo.',
  'location_capture_question':
      'Capturer position na yo mpo na kosalisa ba clients ?',
  'location_business_hint': 'Salela position ya entreprise, esika ya ndako te.',
  'location_capturing': 'Kozwa position...',
  'location_please_wait': 'Zela mwa secondes',
  'location_coords': 'Lat: {lat}, Lng: {lng}',
  'location_accuracy': 'Précision: ±{meters} m',
  'edit_password_title': 'Modifier mot de passe',
  'edit_action': 'Modifier',
  'already_have_account': 'Nazali déjà na compte',
  'delete_product_confirm': 'Olingi kofuta produit oyo ?',
  'delete_product_named': 'Olingi kofuta « {name} » ?',
  'no_photo': 'Photo moko te',
  'no_photo_body': 'Ba produits na photo ebebisi malamu. Koba sans photo ?',
  'continue_without_photo': 'Koba sans photo',
  'display_options': 'Ba options ya affichage',
  'hide_price': 'Bomba prix',
  'show_stock': 'Monisa stock',
  'show_stock_subtitle': 'Monisa motango ya biloko etikali',
  'flash_offer': 'Offre flash',
  'flash_offer_subtitle': 'Badge promo mpe visuels WhatsApp',
  'flash_offer_end': 'Fin ya offre',
  'promo_price_label': 'Prix promo (CDF)',
  'tier_label': 'Palier',
  'retail_type': 'Détail',
  'wholesale_type': 'Gros',
  'take_photo': 'Zwa photo',
  'choose_from_gallery': 'Pona na galerie',
  'filter_all': 'Nionso',
  'choose_product': 'Pona produit',
  'resell_product': 'Zongisa na vente',
  'login_deliveries_required': 'Kota mpo na komona ba livraisons',
  'post_whatsapp_status': 'Poster statut WhatsApp na ngai',
  'shop_active_badge': 'Active',
  'shop_visible_badge': 'Visible',
  'shop_hidden_badge': 'Masquée',
  'today_label': 'Lelo',
  'request_action': 'Kosenga',
  'whatsapp_label': 'WhatsApp',
  'more_items': '+ {count} mosusu...',
  'expected_balance': 'Solde: {amount} CDF',
  'session_since': 'Bandela {date}',
  'sync_failed': 'Sync elongaki te: {error}',
  'error_with_message': 'Erreur: {message}',
  'sold_badge': 'EBEBISI',
  'photo_label': 'Photo',
  'or_label': 'to',
  'clear_all_media': 'Effacer nionso',
  'select_photo_label': 'Photo',
  'permission_location_refused': 'Permission ya localisation eboyami.',
  'next_button': 'Suivant',
  'sync_diagnostics': 'Diagnostics sync',
  'manual_sync': 'Sync manuelle',
  'force_push_all': 'Forcer envoi',
  'full_reset_sync': 'Reset mpe sync',
  'queue_status': 'État ya file',
  'view_queue_details': 'Tala file',
  'open_whatsapp': 'Fungola WhatsApp',
  'share_impossible_colon': 'Partage elongaki te: {error}',
  'action_impossible_colon': 'Action elongaki te: {error}',
  'interactions_count': '{count} interaction(s)',
};

const Map<String, String> secondarySw = {
  'reengage_title': 'Ufuatiliaji wa wateja WhatsApp',
  'reengage_open_whatsapp': 'Fungua WhatsApp',
  'reengage_campaign_done':
      'Kampeni imekamilika. Ufuatiliaji unaofuata baada ya siku 7.',
  'reengage_antispam_limit': 'Kikomo cha kuzuia spam',
  'reengage_next_campaign_in': 'Kampeni inayofuata katika siku {days}.',
  'reengage_message_label': 'Ujumbe',
  'reengage_message_hint': 'Ujumbe wako wa ufuatiliaji…',
  'reengage_limits_info': 'Upeo {max} mawasiliano · kampeni 1 / siku {days}',
  'reengage_consent_title': 'Idhini',
  'reengage_consent_subtitle':
      'Nathibitisha wateja hawa tayari wamewasiliana na duka langu na wanakubali taarifa.',
  'reengage_eligible_clients': 'Wateja wanaostahili ({count})',
  'reengage_no_clients':
      'Hakuna mteja aliye na nambari. Mawasiliano yataonekana baada ya maagizo.',
  'reengage_client_title': 'Mteja {current}/{total}',
  'reengage_client_dialog':
      'Fungua WhatsApp kwa +{phone}?\n\nGusa « Endelea » baada ya kutuma.',
  'reengage_send_progress': 'Inatuma {current}/{total}…',
  'reengage_launch': 'Anza ufuatiliaji ({count})',
  'share_shop_title': 'Shiriki {name}',
  'share_choose_option': 'Chagua chaguo la kushiriki',
  'share_catalog_title': 'Shiriki katalogi',
  'share_catalog_subtitle': 'Bidhaa na kuwasili kwa viungo',
  'share_link_title': 'Shiriki kiungo',
  'share_qr_title': 'Msimbo wa QR wa duka',
  'share_qr_subtitle': 'Ona, shiriki au chapisha',
  'location_security_body':
      'Kwa usalama, tumia eneo la biashara, si la nyumbani.',
  'location_security_footer':
      'Eneo hili litaonekana kwa wateja ili kuwasaidia kupata duka lako.',
  'location_capture_question':
      'Nasa eneo lako la sasa ili kuwasaidia wateja kupata duka lako?',
  'location_business_hint': 'Tumia eneo la biashara, si la nyumbani.',
  'location_capturing': 'Inanasa eneo...',
  'location_please_wait': 'Tafadhali subiri sekunde chache',
  'location_coords': 'Lat: {lat}, Lng: {lng}',
  'location_accuracy': 'Usahihi: ±{meters} m',
  'edit_password_title': 'Badilisha nenosiri',
  'edit_action': 'Hariri',
  'already_have_account': 'Tayari nina akaunti',
  'delete_product_confirm': 'Unataka kufuta bidhaa hii?',
  'delete_product_named': 'Unataka kufuta « {name} »?',
  'no_photo': 'Hakuna picha',
  'no_photo_body':
      'Bidhaa zenye picha zinauzwa zaidi. Endelea bila picha hata hivyo?',
  'continue_without_photo': 'Endelea bila picha',
  'display_options': 'Chaguo za onyesho',
  'hide_price': 'Ficha bei',
  'show_stock': 'Onyesha stoki',
  'show_stock_subtitle': 'Inaonyesha idadi iliyobaki',
  'flash_offer': 'Ofa ya haraka',
  'flash_offer_subtitle': 'Beji ya promo na picha za WhatsApp',
  'flash_offer_end': 'Mwisho wa ofa',
  'promo_price_label': 'Bei ya promo (CDF)',
  'tier_label': 'Kiwango',
  'retail_type': 'Rejareja',
  'wholesale_type': 'Jumla',
  'take_photo': 'Piga picha',
  'choose_from_gallery': 'Chagua kutoka galeri',
  'filter_all': 'Zote',
  'choose_product': 'Chagua bidhaa',
  'resell_product': 'Rudisha kwenye uuzaji',
  'login_deliveries_required': 'Ingia kuona uwasilishaji wako',
  'post_whatsapp_status': 'Chapisha hali yangu ya WhatsApp',
  'shop_active_badge': 'Hai',
  'shop_visible_badge': 'Inaonekana',
  'shop_hidden_badge': 'Imefichwa',
  'today_label': 'Leo',
  'request_action': 'Omba',
  'whatsapp_label': 'WhatsApp',
  'more_items': '+ {count} zaidi...',
  'expected_balance': 'Salio linalotarajiwa: {amount} CDF',
  'session_since': 'Tangu {date}',
  'sync_failed': 'Usawazishaji umeshindwa: {error}',
  'error_with_message': 'Hitilafu: {message}',
  'sold_badge': 'IMEUZWA',
  'photo_label': 'Picha',
  'or_label': 'au',
  'clear_all_media': 'Futa yote',
  'select_photo_label': 'Picha',
  'permission_location_refused': 'Ruhusa ya eneo imekataliwa.',
  'next_button': 'Endelea',
  'sync_diagnostics': 'Uchunguzi wa usawazishaji',
  'manual_sync': 'Sawazisha kwa mkono',
  'force_push_all': 'Lazimisha kutuma yote',
  'full_reset_sync': 'Weka upya na sawazisha',
  'queue_status': 'Hali ya foleni',
  'view_queue_details': 'Tazama foleni',
  'open_whatsapp': 'Fungua WhatsApp',
  'share_impossible_colon': 'Kushiriki kumeshindwa: {error}',
  'action_impossible_colon': 'Hatua imeshindwa: {error}',
  'interactions_count': 'mawasiliano {count}',
};
