// UI strings previously hardcoded in Dart files.
const Map<String, String> uiStringsFr = {
  'sync_in_progress': 'Synchronisation en cours...',
  'code_resent': 'Code renvoyé',
  'close': 'Fermer',
  'confirm': 'Confirmer',
  'payment_received': 'Paiement reçu',
  'delivered': 'Livrée',
  'orders_received': 'Commandes reçues',
  'catalog_preparing': 'Préparation du catalogue…',
  'skip': 'Passer',
  'shop_not_found': 'Boutique introuvable',
  'whatsapp_unavailable': 'Numéro WhatsApp non disponible',
  'shop_name_required': 'Le nom de la boutique est requis',
  'logo_upload_failed': 'Échec de l\'upload du logo',
  'delete_confirm_title': 'Supprimer ?',
  'report_product': 'Signaler ce produit',
  'report_reason': 'Raison du signalement',
  'report_error': 'Erreur lors de l\'envoi du signalement.',
  'report_login_required': 'Connectez-vous pour signaler un produit',
  'give_review': 'Donner mon avis',
  'thanks_review': 'Merci pour votre avis !',
  'publish_review': 'Publier mon avis',
  'report_action': 'Signaler',
  'send': 'Envoyer',
  'copy': 'Copier',
  'direct_call': 'Appel direct',
  'send_sms': 'Envoyer un SMS',
  'mobile_money_payment': 'Paiement Mobile Money',
  'pay_now': 'Payer maintenant',
  'continue_whatsapp': 'Continuer via WhatsApp',
  'ok': 'OK',
  'stock_alert_saved': 'Alerte stock enregistrée',
  'price_alert': 'Alerte prix',
  'restock_alert': 'Alerte retour stock',
  'one_shop_payment': 'Une seule boutique à la fois pour le paiement.',
  'seller_phone_unavailable': 'Numéro vendeur indisponible.',
  'invalid_contact_number': 'Numéro de contact invalide.',
  'phone_unavailable': 'Numéro de téléphone non disponible',
  'edit_shop': 'Modifier ma Boutique',
  'save_changes': 'Enregistrer les modifications',
  'logo': 'Logo',
  'delivery_available': 'Livraison disponible',
  'with_driver': 'Avec chauffeur',
  'quick_publish': 'Publication rapide',
  'publish': 'Publier',
  'tap_add_photo': 'Appuyez pour ajouter une photo',
  'product_name_required': 'Nom du produit requis',
  'add_photo_required': 'Ajoutez au moins une photo',
  'product_published': 'Produit publié !',
  'statistics': 'Statistiques',
  'allow_location': 'Autoriser la localisation',
  'search_title': 'RECHERCHE',
  'category_diagnostic': 'Diagnostic Catégories',
  'no_root_categories': 'Aucune catégorie racine',
  'no_products': 'Aucun produit',
  'update_stock': 'Mettre à jour le stock',
  'request_sent': 'Demande envoyée !',
  'select_product': 'Sélectionnez un produit',
  'update_product': 'Mettre à jour le produit',
  'publish_update': 'Publier la mise à jour',
  'no_product_to_update': 'Aucun produit à mettre à jour',
  'whatsapp_status': 'Statut WhatsApp',
  'manage_my_products': 'Gérer mes produits',
  'change': 'Changer',
  'share_facebook_failed': 'Partage Facebook impossible.',
  'share_failed_retry': 'Partage impossible. Réessayez.',
  'share_images_hint':
      'Images partagées ou téléchargées selon votre navigateur.',
  'tiktok_video_failed': 'Création vidéo TikTok impossible.',
  'open_cash_register': 'Ouvrir la caisse',
  'close_cash_register': 'Fermer la caisse',
  'cash_register_opened': 'Caisse ouverte',
  'cash_register_closed': 'Caisse fermée',
  'cash_management': 'Gestion Caisse',
  'no_shop_available': 'Aucune boutique disponible',
  'session_open': 'Session ouverte',
  'no_transactions': 'Aucune transaction',
  'transactions': 'Transactions',
  'cash': 'Cash',
  'card': 'Carte',
  'open': 'Ouvrir',
  'register': 'Enregistrer',
  'help_support': 'Aide & Support',
  'start_discussion': 'Démarrer la discussion',
  'select_media': 'Veuillez sélectionner un média',
  'slow_connection_retry': 'La connexion est lente. Réessayer?',
  'video': 'Vidéo',
  'security_privacy': 'Sécurité & Confidentialité',
  'understood': 'Compris',
  'locate_shop': 'Localiser la boutique',
  'later': 'Plus tard',
  'capture': 'Capturer',
  'position_captured': 'Position capturée',
  'connection_error': 'Erreur de connexion',
  'clear': 'Effacer',
  'apply': 'Appliquer',
  'share_whatsapp_sms': 'WhatsApp, SMS, réseaux sociaux…',
  'saving': 'Enregistrement...',
  'choose_category': 'Sélectionnez une catégorie',
  'choose_or_create_category': 'Choisir ou créer une catégorie',
  'new_category': 'Nouvelle catégorie…',
  'choose_subcategory': 'Sélectionnez une sous-catégorie',
  'price_on_request_hint': 'Le prix sera affiché comme "Sur demande"',
  'choose_category_required': 'Veuillez choisir ou saisir une catégorie',
  'error_generic': 'Erreur',
  'share_impossible': 'Partage impossible',
  'action_impossible': 'Action impossible',
  'local_shop': 'Boutique locale',
};

const Map<String, String> uiStringsEn = {
  'sync_in_progress': 'Sync in progress...',
  'code_resent': 'Code resent',
  'close': 'Close',
  'confirm': 'Confirm',
  'payment_received': 'Payment received',
  'delivered': 'Delivered',
  'orders_received': 'Orders received',
  'catalog_preparing': 'Preparing catalog…',
  'skip': 'Skip',
  'shop_not_found': 'Shop not found',
  'whatsapp_unavailable': 'WhatsApp number unavailable',
  'shop_name_required': 'Shop name is required',
  'logo_upload_failed': 'Logo upload failed',
  'delete_confirm_title': 'Delete?',
  'report_product': 'Report this product',
  'report_reason': 'Reason for report',
  'report_error': 'Error sending report.',
  'report_login_required': 'Log in to report a product',
  'give_review': 'Leave a review',
  'thanks_review': 'Thanks for your review!',
  'publish_review': 'Publish my review',
  'report_action': 'Report',
  'send': 'Send',
  'copy': 'Copy',
  'direct_call': 'Direct call',
  'send_sms': 'Send SMS',
  'mobile_money_payment': 'Mobile Money payment',
  'pay_now': 'Pay now',
  'continue_whatsapp': 'Continue via WhatsApp',
  'ok': 'OK',
  'stock_alert_saved': 'Stock alert saved',
  'price_alert': 'Price alert',
  'restock_alert': 'Restock alert',
  'one_shop_payment': 'Only one shop at a time for payment.',
  'seller_phone_unavailable': 'Seller number unavailable.',
  'invalid_contact_number': 'Invalid contact number.',
  'phone_unavailable': 'Phone number unavailable',
  'edit_shop': 'Edit my shop',
  'save_changes': 'Save changes',
  'logo': 'Logo',
  'delivery_available': 'Delivery available',
  'with_driver': 'With driver',
  'quick_publish': 'Quick publish',
  'publish': 'Publish',
  'tap_add_photo': 'Tap to add a photo',
  'product_name_required': 'Product name required',
  'add_photo_required': 'Add at least one photo',
  'product_published': 'Product published!',
  'statistics': 'Statistics',
  'allow_location': 'Allow location',
  'search_title': 'SEARCH',
  'category_diagnostic': 'Category diagnostic',
  'no_root_categories': 'No root categories',
  'no_products': 'No products',
  'update_stock': 'Update stock',
  'request_sent': 'Request sent!',
  'select_product': 'Select a product',
  'update_product': 'Update product',
  'publish_update': 'Publish update',
  'no_product_to_update': 'No product to update',
  'whatsapp_status': 'WhatsApp status',
  'manage_my_products': 'Manage my products',
  'change': 'Change',
  'share_facebook_failed': 'Facebook share failed.',
  'share_failed_retry': 'Share failed. Try again.',
  'share_images_hint': 'Images shared or downloaded depending on your browser.',
  'tiktok_video_failed': 'TikTok video creation failed.',
  'open_cash_register': 'Open cash register',
  'close_cash_register': 'Close cash register',
  'cash_register_opened': 'Cash register opened',
  'cash_register_closed': 'Cash register closed',
  'cash_management': 'Cash management',
  'no_shop_available': 'No shop available',
  'session_open': 'Session open',
  'no_transactions': 'No transactions',
  'transactions': 'Transactions',
  'cash': 'Cash',
  'card': 'Card',
  'open': 'Open',
  'register': 'Save',
  'help_support': 'Help & Support',
  'start_discussion': 'Start discussion',
  'select_media': 'Please select media',
  'slow_connection_retry': 'Connection is slow. Retry?',
  'video': 'Video',
  'security_privacy': 'Security & Privacy',
  'understood': 'Got it',
  'locate_shop': 'Locate shop',
  'later': 'Later',
  'capture': 'Capture',
  'position_captured': 'Position captured',
  'connection_error': 'Connection error',
  'clear': 'Clear',
  'apply': 'Apply',
  'share_whatsapp_sms': 'WhatsApp, SMS, social networks…',
  'saving': 'Saving...',
  'choose_category': 'Select a category',
  'choose_or_create_category': 'Choose or create a category',
  'new_category': 'New category…',
  'choose_subcategory': 'Select a subcategory',
  'price_on_request_hint': 'Price will show as "On request"',
  'choose_category_required': 'Please choose or enter a category',
  'error_generic': 'Error',
  'share_impossible': 'Share failed',
  'action_impossible': 'Action failed',
  'local_shop': 'Local shop',
  'follow_sellers_hint': 'Follow sellers to see their new products here',
  'mobile_money': 'Mobile Money',
};

const Map<String, String> uiStringsLn = {
  'sync_in_progress': 'Synchronisation ezali kosala...',
  'code_resent': 'Code etindami lisusu',
  'close': 'Kokanga',
  'confirm': 'Kondima',
  'payment_received': 'Mbongo e reçu',
  'delivered': 'E livré',
  'orders_received': 'Ba commandes e reçues',
  'catalog_preparing': 'Préparation ya catalogue...',
  'skip': 'Ko passer',
  'shop_not_found': 'Boutique ezwami te',
  'whatsapp_unavailable': 'Numéro WhatsApp ezali te',
  'shop_name_required': 'Nkombo ya boutique esengeli',
  'logo_upload_failed': 'Upload ya logo elongaki te',
  'delete_confirm_title': 'Kofuta ?',
  'report_product': 'Signaler produit oyo',
  'report_reason': 'Ntina ya signalement',
  'report_error': 'Erreur na kotinda signalement.',
  'report_login_required': 'Kota mpo na ko signaler',
  'give_review': 'Tia avis na yo',
  'thanks_review': 'Merci mpo na avis na yo !',
  'publish_review': 'Publier avis na ngai',
  'report_action': 'Signaler',
  'send': 'Tinda',
  'copy': 'Kopia',
  'direct_call': 'Benga direct',
  'send_sms': 'Tinda SMS',
  'mobile_money_payment': 'Paiement Mobile Money',
  'pay_now': 'Futa sikoyo',
  'continue_whatsapp': 'Koba na WhatsApp',
  'ok': 'OK',
  'stock_alert_saved': 'Alerte stock enregistrée',
  'price_alert': 'Alerte prix',
  'restock_alert': 'Alerte retour stock',
  'one_shop_payment': 'Boutique moko moko mpo na paiement.',
  'seller_phone_unavailable': 'Numéro vendeur ezali te.',
  'invalid_contact_number': 'Numéro ya contact ezali malamu te.',
  'phone_unavailable': 'Numéro ya téléphone ezali te',
  'edit_shop': 'Modifier boutique na ngai',
  'save_changes': 'Enregistrer ba modifications',
  'logo': 'Logo',
  'delivery_available': 'Livraison ezali',
  'with_driver': 'Na chauffeur',
  'quick_publish': 'Publication ya noki',
  'publish': 'Publier',
  'tap_add_photo': 'Finá mpo na kobakisa photo',
  'product_name_required': 'Nkombo ya produit esengeli',
  'add_photo_required': 'Bakisa photo moko au moins',
  'product_published': 'Produit e publier !',
  'statistics': 'Statistiques',
  'allow_location': 'Pesá localisation',
  'search_title': 'LUKA',
  'category_diagnostic': 'Diagnostic Catégories',
  'no_root_categories': 'Catégorie racine moko te',
  'no_products': 'Produit moko te',
  'update_stock': 'Mettre à jour stock',
  'request_sent': 'Demande etindami !',
  'select_product': 'Pona produit',
  'update_product': 'Mettre à jour produit',
  'publish_update': 'Publier mise à jour',
  'no_product_to_update': 'Produit ya ko mettre à jour moko te',
  'whatsapp_status': 'Statut WhatsApp',
  'manage_my_products': 'Gérer ba produits na ngai',
  'change': 'Changer',
  'share_facebook_failed': 'Partage Facebook elongaki te.',
  'share_failed_retry': 'Partage elongaki te. Meka lisusu.',
  'share_images_hint': 'Ba images e partagées selon navigateur na yo.',
  'tiktok_video_failed': 'Vidéo TikTok elongaki te.',
  'open_cash_register': 'Fungola caisse',
  'close_cash_register': 'Kanga caisse',
  'cash_register_opened': 'Caisse efungolami',
  'cash_register_closed': 'Caisse ekangami',
  'cash_management': 'Gestion Caisse',
  'no_shop_available': 'Boutique moko te',
  'session_open': 'Session efungoli',
  'no_transactions': 'Transaction moko te',
  'transactions': 'Transactions',
  'cash': 'Cash',
  'card': 'Carte',
  'open': 'Fungola',
  'register': 'Enregistrer',
  'help_support': 'Aide & Support',
  'start_discussion': 'Bandela discussion',
  'select_media': 'Pona média',
  'slow_connection_retry': 'Connexion ezali lente. Meka lisusu?',
  'video': 'Vidéo',
  'security_privacy': 'Sécurité & Confidentialité',
  'understood': 'Nayebi',
  'locate_shop': 'Localiser boutique',
  'later': 'Na nsima',
  'capture': 'Capturer',
  'position_captured': 'Position e capturée',
  'connection_error': 'Erreur ya connexion',
  'clear': 'Effacer',
  'apply': 'Appliquer',
  'share_whatsapp_sms': 'WhatsApp, SMS, réseaux sociaux…',
  'saving': 'Enregistrement...',
  'choose_category': 'Pona catégorie',
  'choose_or_create_category': 'Pona to créer catégorie',
  'new_category': 'Catégorie ya sika…',
  'choose_subcategory': 'Pona sous-catégorie',
  'price_on_request_hint': 'Prix ekolakisama "Sur demande"',
  'choose_category_required': 'Pona to tia catégorie',
  'error_generic': 'Erreur',
  'share_impossible': 'Partage elongaki te',
  'action_impossible': 'Action elongaki te',
  'local_shop': 'Boutique locale',
};

const Map<String, String> uiStringsSw = {
  'sync_in_progress': 'Usawazishaji unaendelea...',
  'code_resent': 'Msimbo umetumwa tena',
  'close': 'Funga',
  'confirm': 'Thibitisha',
  'payment_received': 'Malipo yamepokelewa',
  'delivered': 'Imewasilishwa',
  'orders_received': 'Maagizo yaliyopokelewa',
  'catalog_preparing': 'Inaandaa katalogi…',
  'skip': 'Ruka',
  'shop_not_found': 'Duka halijapatikana',
  'whatsapp_unavailable': 'Nambari ya WhatsApp haipatikani',
  'shop_name_required': 'Jina la duka linahitajika',
  'logo_upload_failed': 'Upakiaji wa nembo umeshindwa',
  'delete_confirm_title': 'Futa?',
  'report_product': 'Ripoti bidhaa hii',
  'report_reason': 'Sababu ya ripoti',
  'report_error': 'Hitilafu kutuma ripoti.',
  'report_login_required': 'Ingia ili kuripoti bidhaa',
  'give_review': 'Toa maoni',
  'thanks_review': 'Asante kwa maoni yako!',
  'publish_review': 'Chapisha maoni langu',
  'report_action': 'Ripoti',
  'send': 'Tuma',
  'copy': 'Nakili',
  'direct_call': 'Simu ya moja kwa moja',
  'send_sms': 'Tuma SMS',
  'mobile_money_payment': 'Malipo ya Mobile Money',
  'pay_now': 'Lipa sasa',
  'continue_whatsapp': 'Endelea kupitia WhatsApp',
  'ok': 'OK',
  'stock_alert_saved': 'Arifa ya stoki imehifadhiwa',
  'price_alert': 'Arifa ya bei',
  'restock_alert': 'Arifa ya kurudi stoki',
  'one_shop_payment': 'Duka moja kwa wakati kwa malipo.',
  'seller_phone_unavailable': 'Nambari ya muuzaji haipatikani.',
  'invalid_contact_number': 'Nambari ya mawasiliano si sahihi.',
  'phone_unavailable': 'Nambari ya simu haipatikani',
  'edit_shop': 'Hariri duka langu',
  'save_changes': 'Hifadhi mabadiliko',
  'logo': 'Nembo',
  'delivery_available': 'Uwasilishaji unapatikana',
  'with_driver': 'Na dereva',
  'quick_publish': 'Uchapishaji wa haraka',
  'publish': 'Chapisha',
  'tap_add_photo': 'Gusa kuongeza picha',
  'product_name_required': 'Jina la bidhaa linahitajika',
  'add_photo_required': 'Ongeza angalau picha moja',
  'product_published': 'Bidhaa imechapishwa!',
  'statistics': 'Takwimu',
  'allow_location': 'Ruhusu eneo',
  'search_title': 'TAFUTA',
  'category_diagnostic': 'Uchunguzi wa kategoria',
  'no_root_categories': 'Hakuna kategoria za msingi',
  'no_products': 'Hakuna bidhaa',
  'update_stock': 'Sasisha stoki',
  'request_sent': 'Ombi limetumwa!',
  'select_product': 'Chagua bidhaa',
  'update_product': 'Sasisha bidhaa',
  'publish_update': 'Chapisha sasisho',
  'no_product_to_update': 'Hakuna bidhaa ya kusasisha',
  'whatsapp_status': 'Hali ya WhatsApp',
  'manage_my_products': 'Simamia bidhaa zangu',
  'change': 'Badilisha',
  'share_facebook_failed': 'Kushiriki Facebook kumeshindwa.',
  'share_failed_retry': 'Kushiriki kumeshindwa. Jaribu tena.',
  'share_images_hint': 'Picha zimeshirikiwa au kupakuliwa kulingana na kivinjari.',
  'tiktok_video_failed': 'Uundaji wa video ya TikTok umeshindwa.',
  'open_cash_register': 'Fungua rejista',
  'close_cash_register': 'Funga rejista',
  'cash_register_opened': 'Rejista imefunguliwa',
  'cash_register_closed': 'Rejista imefungwa',
  'cash_management': 'Usimamizi wa rejista',
  'no_shop_available': 'Hakuna duka',
  'session_open': 'Kipindi wazi',
  'no_transactions': 'Hakuna miamala',
  'transactions': 'Miamala',
  'cash': 'Taslimu',
  'card': 'Kadi',
  'open': 'Fungua',
  'register': 'Hifadhi',
  'help_support': 'Msaada',
  'start_discussion': 'Anza mazungumzo',
  'select_media': 'Tafadhali chagua media',
  'slow_connection_retry': 'Muunganisho ni polepole. Jaribu tena?',
  'video': 'Video',
  'security_privacy': 'Usalama na Faragha',
  'understood': 'Nimeelewa',
  'locate_shop': 'Tambua duka',
  'later': 'Baadaye',
  'capture': 'Nasa',
  'position_captured': 'Eneo limenaswa',
  'connection_error': 'Hitilafu ya muunganisho',
  'clear': 'Futa',
  'apply': 'Tumia',
  'share_whatsapp_sms': 'WhatsApp, SMS, mitandao ya kijamii…',
  'saving': 'Inahifadhi...',
  'choose_category': 'Chagua kategoria',
  'choose_or_create_category': 'Chagua au unda kategoria',
  'new_category': 'Kategoria mpya…',
  'choose_subcategory': 'Chagua kategoria ndogo',
  'price_on_request_hint': 'Bei itaonyeshwa kama "Kwa ombi"',
  'choose_category_required': 'Chagua au andika kategoria',
  'error_generic': 'Hitilafu',
  'share_impossible': 'Kushiriki kumeshindwa',
  'action_impossible': 'Hatua imeshindwa',
  'local_shop': 'Duka la ndani',
  'follow_sellers_hint': 'Fuata wauzaji kuona bidhaa zao mpya hapa',
  'mobile_money': 'Mobile Money',
};
